//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBevInc
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Recipe
    {
        public Nullable<double> FGID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> RMID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Finished_Goods Finished_Goods { get; set; }
        public virtual Raw_Materials Raw_Materials { get; set; }
    }
}
